import { AppError } from "./types.js";

export class FilesApiClient {
  constructor(private fetcher: typeof fetch = fetch) {}
  private config() { const key = process.env.DEEPSEEK_API_KEY; if (!key) throw new AppError("deepseek_not_configured", "DEEPSEEK_API_KEY is not configured", 503); return { key, root: (process.env.DEEPSEEK_BASE_URL ?? "https://api.deepseek.com").replace(/\/+$/, "") }; }
  async list() { return this.call("/files", { method: "GET" }); }
  async remove(id: string) { if (!/^[A-Za-z0-9_-]{1,200}$/.test(id)) throw new AppError("invalid_file_id", "Invalid file id"); return this.call(`/files/${encodeURIComponent(id)}`, { method: "DELETE" }); }
  async upload(input: unknown) {
    if (!input || typeof input !== "object") throw new AppError("invalid_file", "File body is required"); const body = input as Record<string, unknown>;
    if (typeof body.name !== "string" || typeof body.contentBase64 !== "string") throw new AppError("invalid_file", "name and contentBase64 are required");
    const mediaType = typeof body.mediaType === "string" ? body.mediaType.toLowerCase() : ""; if (!new Set(["image/jpeg", "image/png", "image/gif", "image/webp"]).has(mediaType)) throw new AppError("unsupported_media_type", "Only JPEG, PNG, GIF and WebP images are supported", 415);
    const encoded = body.contentBase64.replace(/\s/g, ""); if (!encoded || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(encoded)) throw new AppError("invalid_file", "contentBase64 is invalid"); const bytes = Buffer.from(encoded, "base64"); if (!bytes.length || bytes.toString("base64") !== encoded) throw new AppError("invalid_file", "contentBase64 is invalid"); if (bytes.length > Number(process.env.MAX_IMAGE_BYTES ?? 10_000_000)) throw new AppError("file_too_large", "File is too large", 413); const signatureMatches = mediaType === "image/jpeg" ? bytes.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff])) : mediaType === "image/png" ? bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) : mediaType === "image/gif" ? ["GIF87a", "GIF89a"].includes(bytes.subarray(0, 6).toString("ascii")) : bytes.subarray(0, 4).toString("ascii") === "RIFF" && bytes.subarray(8, 12).toString("ascii") === "WEBP"; if (!signatureMatches) throw new AppError("invalid_file", "Image bytes do not match mediaType", 415);
    const purpose = body.purpose ?? "user_data"; if (purpose !== "user_data") throw new AppError("invalid_file", "purpose must be user_data"); const expires = body.expiresAfterSeconds; if (expires !== undefined && expires !== null && (!Number.isInteger(expires) || (expires as number) < 3600 || (expires as number) > 2_592_000)) throw new AppError("invalid_file", "expiresAfterSeconds must be null or an integer from 3600 to 2592000"); const form = new FormData(); form.append("file", new Blob([bytes], { type: mediaType }), body.name); form.append("purpose", purpose); if (typeof expires === "number") { form.append("expires_after[anchor]", "created_at"); form.append("expires_after[seconds]", String(expires)); }
    return this.call("/files", { method: "POST", body: form });
  }
  private async call(path: string, init: RequestInit) { const { key, root } = this.config(); const response = await this.fetcher(`${root}${path}`, { ...init, headers: { authorization: `Bearer ${key}`, ...(init.headers ?? {}) }, signal: AbortSignal.timeout(60_000) }); const text = await response.text(); let body: unknown; try { body = JSON.parse(text); } catch { body = { message: text.slice(0, 500) }; } if (!response.ok) throw new AppError("files_api_error", `Files API returned ${response.status}`, response.status, response.status === 429 || response.status >= 500); return body; }
}
