import { createHash, createPrivateKey, randomUUID, sign } from "node:crypto";
import { connect } from "node:http2";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { AppError, type TaskRun, type ScheduledTask } from "./types.js";

export interface PushRegistration { id: string; userId: string; token: string; kind: "device" | "live_activity"; environment: "sandbox" | "production"; operationId?: string; activityId?: string; updatedAt: string }
interface PushData { registrations: PushRegistration[] }
export class PushStore {
  private queue: Promise<unknown> = Promise.resolve();
  constructor(private file = process.env.PUSH_FILE ?? join(process.cwd(), "data", "push.json")) {}
  private async read(): Promise<PushData> { try { return JSON.parse(await readFile(this.file, "utf8")) as PushData; } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return { registrations: [] }; throw e; } }
  async register(userId: string, raw: unknown, kind: PushRegistration["kind"] = "device") {
    if (!raw || typeof raw !== "object") throw new AppError("invalid_push_token", "Push registration body is required"); const input = raw as Record<string, unknown>; const token = typeof input.token === "string" ? input.token.replace(/[<>\s]/g, "") : ""; const environment = input.environment === "production" ? "production" : "sandbox";
    if (!/^[A-Fa-f0-9]{32,512}$/.test(token)) throw new AppError("invalid_push_token", "Invalid APNs token"); if (input.environment !== undefined && !["sandbox", "production"].includes(String(input.environment))) throw new AppError("invalid_push_token", "environment must be sandbox or production"); const operationId = typeof input.operationId === "string" && input.operationId.length <= 200 ? input.operationId : undefined; const activityId = typeof input.activityId === "string" && input.activityId.length <= 200 ? input.activityId : undefined; if (kind === "live_activity" && !activityId) throw new AppError("invalid_push_token", "activityId is required for Live Activity tokens"); let record!: PushRegistration;
    const job = this.queue.then(async () => { const data = await this.read(); record = { id: randomUUID(), userId, token, kind, environment, updatedAt: new Date().toISOString(), ...(operationId ? { operationId } : {}), ...(activityId ? { activityId } : {}) }; data.registrations = data.registrations.filter(r => !(r.userId === userId && r.token === token && r.kind === kind)); data.registrations.push(record); await mkdir(dirname(this.file), { recursive: true }); const tmp = `${this.file}.${process.pid}.tmp`; await writeFile(tmp, JSON.stringify(data)); await rename(tmp, this.file); }); this.queue = job.catch(() => undefined); await job; return record;
  }
  async list(userId: string, kind?: PushRegistration["kind"]) { return (await this.read()).registrations.filter(r => r.userId === userId && (!kind || r.kind === kind)); }
  async unregister(userId: string, raw: unknown, kind?: PushRegistration["kind"]) {
    if (!raw || typeof raw !== "object") throw new AppError("invalid_push_token", "Push token body is required");
    const token = typeof (raw as Record<string, unknown>).token === "string" ? String((raw as Record<string, unknown>).token).replace(/[<>\s]/g, "") : "";
    if (!/^[A-Fa-f0-9]{32,512}$/.test(token)) throw new AppError("invalid_push_token", "Invalid APNs token");
    let removed = false;
    const job = this.queue.then(async () => { const data = await this.read(); const before = data.registrations.length; data.registrations = data.registrations.filter(r => !(r.userId === userId && r.token === token && (!kind || r.kind === kind))); removed = data.registrations.length !== before; await mkdir(dirname(this.file), { recursive: true }); const tmp = `${this.file}.${process.pid}.tmp`; await writeFile(tmp, JSON.stringify(data)); await rename(tmp, this.file); });
    this.queue = job.catch(() => undefined); await job; return removed;
  }
  async removeToken(token: string) { const job = this.queue.then(async () => { const data = await this.read(); data.registrations = data.registrations.filter(r => r.token !== token); await mkdir(dirname(this.file), { recursive: true }); const tmp = `${this.file}.${process.pid}.tmp`; await writeFile(tmp, JSON.stringify(data)); await rename(tmp, this.file); }); this.queue = job.catch(() => undefined); await job; }
}

const b64url = (value: string | Buffer) => Buffer.from(value).toString("base64url");
export class ApnsSender {
  private cached?: { jwt: string; created: number };
  constructor(private store: PushStore) {}
  private credentials() { const teamId = process.env.APNS_TEAM_ID, keyId = process.env.APNS_KEY_ID, topic = process.env.APNS_TOPIC, rawKey = process.env.APNS_PRIVATE_KEY; if (!teamId || !keyId || !topic || !rawKey) throw new AppError("apns_not_configured", "APNs credentials are not configured", 503); return { teamId, keyId, topic, key: rawKey.replace(/\\n/g, "\n") }; }
  private jwt() { const now = Math.floor(Date.now() / 1000); if (this.cached && now - this.cached.created < 3000) return this.cached.jwt; const c = this.credentials(); const header = b64url(JSON.stringify({ alg: "ES256", kid: c.keyId })); const payload = b64url(JSON.stringify({ iss: c.teamId, iat: now })); const signature = sign("sha256", Buffer.from(`${header}.${payload}`), { key: createPrivateKey(c.key), dsaEncoding: "ieee-p1363" }); const jwt = `${header}.${payload}.${b64url(signature)}`; this.cached = { jwt, created: now }; return jwt; }
  async send(registration: PushRegistration, payload: object, options: { live?: boolean; event?: "start" | "update" | "end" } = {}) {
    const c = this.credentials(); const origin = registration.environment === "production" ? "https://api.push.apple.com" : "https://api.sandbox.push.apple.com"; const topic = options.live ? `${c.topic}.push-type.liveactivity` : c.topic;
    const encodedPayload = JSON.stringify(payload); if (Buffer.byteLength(encodedPayload) > 4_096) throw new AppError("push_payload_too_large", "APNs payload exceeds 4 KB", 413);
    const result = await new Promise<{ status: number; body: string }>((resolve, reject) => { const session = connect(origin); session.setTimeout(15_000, () => session.destroy(new Error("APNs timeout"))); session.once("error", reject); const request = session.request({ ":method": "POST", ":path": `/3/device/${registration.token}`, authorization: `bearer ${this.jwt()}`, "apns-topic": topic, "apns-push-type": options.live ? "liveactivity" : "alert", "apns-priority": options.live ? "5" : "10" }); let body = ""; let status = 0; request.setEncoding("utf8"); request.on("response", headers => { status = Number(headers[":status"] ?? 0); }); request.on("data", chunk => body += chunk); request.on("end", () => { session.close(); resolve({ status, body }); }); request.once("error", error => { session.close(); reject(error); }); request.end(encodedPayload); });
    if (result.status === 410 || result.status === 400 && result.body.includes("BadDeviceToken")) await this.store.removeToken(registration.token); if (result.status < 200 || result.status >= 300) throw new AppError("apns_error", `APNs returned ${result.status}: ${result.body.slice(0, 200)}`, 502, result.status >= 500); return result;
  }
  async notifyTask(task: ScheduledTask, run: TaskRun): Promise<"not_requested" | "not_configured" | "no_devices" | "sent" | "failed"> { if (!task.notify) return "not_requested"; const registrations = await this.store.list(task.userId, "device"); if (!registrations.length) return "no_devices"; try { this.credentials(); } catch (e) { if (e instanceof AppError && e.code === "apns_not_configured") return "not_configured"; throw e; } const title = task.title.slice(0, 120), body = (run.output ?? run.error ?? run.status).slice(0, 200); const results = await Promise.allSettled(registrations.map(r => this.send(r, { aps: { alert: { title, body }, sound: "default" }, taskId: task.id, runId: run.id, task_id: task.id, run_id: run.id }))); return results.some(result => result.status === "fulfilled") ? "sent" : "failed"; }
  async updateLiveActivity(userId: string, operationOrActivityId: string, input: unknown) { const registrations = (await this.store.list(userId, "live_activity")).filter(r => r.operationId === operationOrActivityId || r.activityId === operationOrActivityId); if (!registrations.length) throw new AppError("not_found", "Live Activity token not found", 404); if (!input || typeof input !== "object") throw new AppError("invalid_live_activity", "Update body is required"); const body = input as Record<string, unknown>; const event = body.event === "end" ? "end" : "update"; if (!body.contentState || typeof body.contentState !== "object" || Array.isArray(body.contentState)) throw new AppError("invalid_live_activity", "contentState is required"); const aps: Record<string, unknown> = { timestamp: Math.floor(Date.now() / 1000), event, "content-state": body.contentState }; if (typeof body.staleDate === "number") aps["stale-date"] = body.staleDate; if (typeof body.dismissalDate === "number") aps["dismissal-date"] = body.dismissalDate; if (body.alert && typeof body.alert === "object") aps.alert = body.alert; const results = await Promise.allSettled(registrations.map(r => this.send(r, { aps, activity_id: r.activityId, operation_id: r.operationId }, { live: true, event }))); return { sent: results.filter(r => r.status === "fulfilled").length, failed: results.filter(r => r.status === "rejected").length }; }
}
